#!/bin/sh
#PBS -A prismsproject_flux
#PBS -N Micro
#PBS -l nodes=1:ppn=16,walltime=48:00:00,pmem=3800mb,qos=flux
#PBS -q flux
#PBS -m abe
#PBS -V
#PBS -M greght@umich.edu
echo "I ran on:"
module load intel-comp/12.1
module load mkl
export LD_LIBRARY_PATH=/home/rudraa/software/numerics/petsc-3.3-p6/shared-optimized/lib:$LD_LIBRARY_PATH
# Create a local directory to run and copy your files to local.
# Let PBS handle your output
cd /
mpiexec -np 16 ./exe -pc_type hypre 

#For submission
#qsub pbsJob
#For submission to dynamic command line output
#qsub -k oe pbsJob
#qstat -u greght
#qprims 
#qdel uid
