#ifndef INCLUDE_CRYSTALPLASTICITY_TEMPLATE_INSTANTIATIONS_H_
#define INCLUDE_CRYSTALPLASTICITY_TEMPLATE_INSTANTIATIONS_H_

#ifndef CRYSTALPLASTICITY_TEMPLATE_INSTANTIATION
#define CRYSTALPLASTICITY_TEMPLATE_INSTANTIATION
template class crystalPlasticity<2>;
template class crystalPlasticity<3>;
#endif

#endif /* INCLUDE_ELLIPTICBVP_TEMPLATE_INSTANTIATIONS_H_ */
