#ifndef INCLUDE_ELLIPTICBVP_TEMPLATE_INSTANTIATIONS_H_
#define INCLUDE_ELLIPTICBVP_TEMPLATE_INSTANTIATIONS_H_

#ifndef ELLIPTICBVP_TEMPLATE_INSTANTIATION
#define ELLIPTICBVP_TEMPLATE_INSTANTIATION
template class ellipticBVP<2>;
template class ellipticBVP<3>;
#endif

#endif /* INCLUDE_ELLIPTICBVP_TEMPLATE_INSTANTIATIONS_H_ */
